version: '3'
services:
  web:
    image: offlinegmbh/laravel-php7.0
    ports:
      - 8888:80
    restart: always
    command: sh /docker/scripts/install.sh
    tty: true
    stdin_open: true
    links:
      - db
    volumes:
      - ./:/var/www
      - ./docker/scripts/install.sh:/docker/scripts/install.sh
      - ./docker/scripts/start_cron.sh:/start_cron.sh
      - ./data/logs/apache:/var/log/apache2
      - ./docker/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf

  db:
    image: dydx/alpine-mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/conf/my.cnf:/etc/my.cnf
      - ./docker/scripts/mariadb_init.sh:/mariadb_init.sh
      - ./docker/scripts/run.sh:/run.sh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: erik
      MYSQL_PASSWORD: skipjack
      MYSQL_DATABASE: database_1


